name: resident
description: "A general payment plaform"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2036

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.3.1
  logger: any
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0
  pinput: ^5.0.0
  otp_timer_button: ^1.1.1
  lottie: ^3.1.2
  intl: ^0.19.0
  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master
  grouped_list: ^6.0.0
  image_picker: ^1.0.8
  http: ^1.2.0
  flutter_native_contact_picker_plus: ^0.0.3
  webview_flutter: ^4.8.0
  delightful_toast: ^1.1.0
  currency_symbols: ^0.0.1+2
  liquid_pull_to_refresh: ^3.0.1
  dropdown_button2: ^2.3.9
  permission_handler: ^11.3.1
  flutter_phoenix: ^1.1.1
  app_version_update: ^6.0.0

  


dependency_overrides:
  web: ^1.0.0
  permission_handler_html:
    git:
      url: https://github.com/hpoul/flutter-permission-handler.git
      path: permission_handler_html
      ref: permissiondescriptor

      
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Mulish
        fonts:
          - asset: assets/fonts/Mulish-Black.ttf
          - asset: assets/fonts/Mulish-BlackItalic.ttf
          # - asset: assets/fonts/Mulish-ExtLtIta.ttf
          - asset: assets/fonts/Mulish-Bold.ttf
          - asset: assets/fonts/Mulish-BoldItalic.ttf
          - asset: assets/fonts/Mulish-ExtraBold.ttf
          - asset: assets/fonts/Mulish-ExtraBoldItalic.ttf
          - asset: assets/fonts/Mulish-ExtraLight.ttf
          - asset: assets/fonts/Mulish-ExtraLightItalic.ttf
          - asset: assets/fonts/Mulish-Italic.ttf
          - asset: assets/fonts/Mulish-Light.ttf
          - asset: assets/fonts/Mulish-LightItalic.ttf
          - asset: assets/fonts/Mulish-Medium.ttf
          - asset: assets/fonts/Mulish-MediumItalic.ttf
          - asset: assets/fonts/Mulish-Regular.ttf
          - asset: assets/fonts/Mulish-SemiBold.ttf
          - asset: assets/fonts/Mulish-SemiBoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  
