name: iOS Build

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main  # Optional: If you want to trigger the build on PRs as well

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner with the latest Xcode

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter manually (clone the stable channel)
      - name: Install Flutter
        run: |
          # Clone Flutter SDK from GitHub and checkout the stable channel
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter --version

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          sudo gem install cocoapods
          pod install

      # Build the app using Flutter (this will build for iOS)
      - name: Build iOS app with Flutter
        run: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      # Upload the .ipa to GitHub Release using softprops/action-gh-release
      - name: Upload .ipa to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/ipa/resident.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
