name: iOS Build

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main  # Optional: If you want to trigger the build on PRs as well

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner with the latest Xcode

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Flutter setup action
        with:
          flutter-version: '3.5'  # Specify the Flutter version you want to use

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          sudo gem install cocoapods
          pod install

      # Build the app using Flutter (this will build for iOS)
      - name: Build iOS app with Flutter
        run: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      # Upload the .ipa to artifacts (updated to v3)
      - name: Upload .ipa to artifacts
        uses: actions/upload-artifact@latest  # Updated to v3 to avoid deprecated version
        with:
          name: Resident-build
          path: build/ios/ipa/resident.ipa  # Adjust the path to your .ipa file location
