name: iOS Build and Release

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main  # Optional: If you want to trigger the build on PRs as well
  # Also trigger on tag creation for releases
  # If you want to create a release manually, you can create a tag via `git tag` command
  create:
    tags:
      - '*'  # Any tag triggers the release

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner with the latest Xcode

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter (latest stable version)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      # Clean and install dependencies
      - name: Flutter clean and pub get
        run: |
          flutter clean
          flutter pub get

      # Ensure Podfile exists and install dependencies
      - name: Ensure Podfile exists and install CocoaPods
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Podfile is missing. Creating a new one..."
            flutter create .
          fi
          cd ios
          sudo gem install cocoapods
          pod install

      # Build the app for iOS
      - name: Build iOS app with Flutter
        run: |
          flutter build ios --release --no-codesign

      # Create a Git tag (if not already created in a previous step)
      - name: Create Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Or you can use a version from your `pubspec.yaml`
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Upload the .ipa to GitHub Release
      - name: Upload .ipa to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/ipa/resident.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

