name: Build and Release iOS App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Optional: If you want to trigger the build on PRs

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner with the latest Xcode

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter (latest stable version)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # Specify the Flutter version you want to use

      # Clean and install dependencies
      - name: Flutter clean and pub get
        run: |
          flutter clean
          flutter pub get

      # Ensure Podfile exists and install CocoaPods
      - name: Ensure Podfile exists and install CocoaPods
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Podfile is missing. Creating a new one..."
            flutter create .
          fi
          cd ios
          sudo gem install cocoapods
          pod install

      # Build the app for iOS
      - name: Build iOS app with Flutter
        run: |
          flutter build ios --release --no-codesign

      # Create Git tag
      - name: Create Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Or you can use a version from your `pubspec.yaml`
          git tag $TAG_NAME
          git remote set-url origin https://x-access-token:${{ secrets.GH_PATT }}@github.com/${{ github.repository }}.git
          git push origin $TAG_NAME  # Push the tag to the repository
        env:
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.24.4-arm64
          PUB_CACHE: /Users/runner/.pub-cache


      # Upload .ipa to GitHub Release
      - name: Upload .ipa to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/ipa/resident.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use default token here for release action
